import html from "html-literal";
import flag from "../../assets/images/grc.png";
export default state => html`
  <div class="countryInfo" id="greeceInfo">
    <div class="metaDataContainer">
      <img
        class="shortCountryInfoFlag"
        id="greeceInfoFlag"
        src=${flag}
        alt="The
        Flag
        of
        Greece"
      />
      <div class="genInformationContainer">
      <p class="genInfoRegion">
          <u>${state.info.name}</u> Is Located In The Region of
          <u>${state.info.region}</u><br />
          And The Subregion of <u>${state.info.subregion}</u>
        </p>
        <p class="genInfoSubRegion"></p>
        <p class="genInfoCapitolCity">
          The Capitol of <u>${state.info.name}</u> is
          <u>${state.info.Capital}</u><br></br>
          <u>${state.info.Capital}</u> is located at<br> Lat: <u>${
  state.Weather.lat
}</u> Lon: <u>${state.Weather.lon}</u><br><br>

          Here is a look at the current weather in <br><u>${
            state.info.Capital
          }</u>: <br><br>
          The Temperature is currently: °F ${state.main.temp}<br>
          But it feels like: °F ${state.main.feels_like} <br> and
         ${state.Weather.description.map(weatherBlock)}


        <p>
          The Population of <u>${state.info.name}</u> is is approx.
          <u>${state.info.population}</u>
        </p>
        <p class="genInfoISOCodes ">
          <u>${state.info.name}'s</u> 2 Digit Alpha code is:
          <u>${state.info.Alpha2Code}</u><br />
          <u>${state.info.name}'s</u> 3 Digit Alpha code is:
          <u>${state.info.Alpha3Code}</u>
        </p>
        <p class="genInfoCurrency">
          The National Currency of ${state.info.name} Is: <br />
          The <u>${state.info.Currency[0].name}</u> Represented As:
          <u>${state.info.Currency[0].symbol}</u> &
          <u>${state.info.Currency[0].code}</u>
        </p>
        <p class="genInfoCallingCodes">
          <u>${state.info.name}'s</u> calling code is
          <u>${state.info.callingCodes}</u>
        </p>
        <p class="genInfoTimezones">
          Timezones: <u>${state.info.timezones}</u>
        </p>
      </div>
    </div>
      <div>
        <h1 class="countryNameHeader">${state.info.name}</h1>
        <h2 class="nativeName">${state.info.nativeName}</h2>
      </div>
      <section class="history topic" id="greeceHistory">
        <h3>
          History
        </h3>
        <h4>
        Greece during the Byzantine period (c. 300 CE–c. 1453)
        </h4>
        <h4>
        Late Roman administration
        </h4>
        <P>
        At the beginning of the 4th century, the regions comprised by the modern state of Greece were divided into eight provinces: Rhodope, Macedonia, Epirus (Ípeiros) Nova, Epirus Vetus, Thessaly (Thessalía), Achaea, Crete (Kríti), and the Islands (Insulae). Of the eight provinces, all except Rhodope and the Islands were a part of the larger diocese of Moesia, which extended to the Danube River in the north. (The word diocese originally referred to a governmental area governed by a Roman imperial vicar. The secular diocese was subdivided into provinces, each with its own governor.) Rhodope belonged to the diocese of Thrace (Thráki), and the Islands were classed as part of the diocese of Asiana, consisting of the westernmost provinces of Asia Minor. By the early years of the 5th century, administrative readjustments had divided the older diocese of Moesia into two sections, creating in the north the diocese of Dacia and in the south that of Macedonia, made up of the provinces of Macedonia I and II, with Epirus Novus and Epirus Vetus, Thessaly, Achaea, and Crete. Further changes during the middle of the 6th century resulted in the establishment of a military command known as the quaestura exercitus, a zone made up of the Islands and Caria, from the diocese of Asiana, together with the province of Moesia II on the Danube; it was designed as a means of providing for the armies based along the northern frontier in regions that were too impoverished or devastated to adequately support them.<br>
        In turn, these diocesan groups were parts of larger administrative units—the praetorian prefectures. Most of the Greek provinces were in the praetorian prefecture of Illyricum, except Rhodope, which, as a province of the diocese of Thrace, was in the prefecture of Oriens, as were the Islands. This pattern was radically altered by the developments of the 7th century.<br>
        Some of the ancient names for the regions of Greece disappeared from everyday use. However, many continued to be used in literary and administrative contexts, especially in the administration of the church, or were revived by classicizing writers of the late Byzantine period. Thus, Aitolia, Akarnania, Achaea, Arcadia (Arkadía), and Lakedaimon were used in the 13th century and after. Similarly, in central Greece, Boeotia (Voiotía), Euboea (Évvoia), and Thessaly all survived but in different contexts. Typical of their history is Euboea, which was so called until the 8th century, after which it was referred to variously as Chalkis or Euripus. Western writers after 1204 identified it as Negroponte (“Black Bridge,” after the bridge connecting it to the mainland), although the Byzantines also called it Euboea. The names Epirus and Macedonia never dropped out of regular use. However, many new names were also coined during the Byzantine period; these tended to be geographic descriptions (such as Strymon [Strimón] or Boleron) used for both provincial and administrative divisions as well as to describe regions with a particular ethnic composition—for example, Vlachia in southern Thessaly.
        </P>
        <h5>The evolution of Byzantine institutions</h5>
        <P>
        As in other parts of the Roman world, the function of cities in the administrative structure of the state underwent a gradual evolution from the 3rd century on as the central government found it increasingly necessary to intervene in municipal affairs in order to gain revenues. This need for intervention developed when the vitality of cities became eroded as a result of a range of factors, notably the economic damage to urban infrastructures that accompanied the civil wars and barbarian inroads of the 3rd century. The so-called “decline” of the curial order (the strata of local government officials known as decurions), caused by the weakening of the fiscal and economic independence of many towns by the tendency of urban elites to avoid municipal obligations, also played a role. Finally, in the eastern parts of the empire, the transformation of Byzantium into Constantinople as a new imperial capital in 330 had important results for patterns of internal trade and commerce as well as for social relations between provincial elites and the state. Nevertheless, the cities of the southern Balkans were able to survive the raids and devastation of both Goths and Huns in the 4th and 5th centuries, and there is no evidence that cities ceased to carry on their function as centres of market activity, local administration, and social life. Those cities that were artificial, or purely administrative creations of the Roman state, were the first to suffer, and, under difficult conditions, they generally disappeared. On the other hand, the state—through its regional and central military administration—also appears to have been involved in promoting different types of smaller defended urban centres, which were better adapted to these conditions.<br>

        In the 7th century a series of developments combined to further promote what was already in the process of becoming a radically different pattern of settlement and administration. In the first place, the results of the long-term developments already referred to, in terms of both social and economic stability, were factors. In particular, the municipal landowning elites transferred their attention—especially with respect to investment in the imperial system—away from their local cities to the imperial capital. In the second place, the economic disruption brought about by the infiltration of large numbers of Slav settlers and immigrants was exacerbated by the devastation and insecurity caused by the wars between the empire and the Avars, a Turco-Mongol confederacy that was able, from the 560s to the 630s, to harness the resources of those peoples in the plains of Hungary and in the Balkans to launch a series of extremely damaging and disruptive attacks on the Eastern Empire. Although the disruptions of the earlier invasions of the Huns and the Goths may have been as damaging in the short term, the Balkans were by this time suffering from the cumulative effects both of two centuries of constant insecurity and warfare and of endemic plague, which had struck the Eastern Empire in the 540s. It is clear from the imperial legislation of the late 5th and early 6th centuries dealing with the Danubian provinces and with Thrace, as well as from the archaeological record, that the final results of this economic disruption were to bring about the abandonment of the traditional pattern of urban economies. Even the construction of churches, which had experienced a certain efflorescence during the 6th century, virtually ceased in the 7th century. Secular construction also stopped, an extended process of ruralization of settlement and of economic life took place, and new populations penetrated far into the Peloponnese. The extent to which these new settlers replaced, or were able to live alongside, the indigenous population remains unclear.<br>

        As a consequence of these changes, the traditional administration collapsed, chiefly because the government at Constantinople could control only the coastal plains and some river valleys. The cities that remained in imperial hands, such as Corinth (Kórinthos) and Thessalonica (Thessaloníki), for example, were well-defended fortresses or had access to the sea, whence they could be supplied. Inland, tribal groupings and chieftaincies (sklaviniai) dominated many districts, and, though it appears that the empire claimed political sovereignty over such regions, it was rarely able to make this effective or to extract regular revenues, although tributes were obtained at times. The sklaviniai, however, did not control the entire inland region; there were many areas in which the indigenous population and the traditional patterns of local social structure and political organization may have survived and where imperial authority may have been recognized. The evidence is too sparse to draw definite conclusions.<br>

        Evidence for the degree of Byzantine control over the area is reflected dimly in the lists of signatories to ecclesiastical councils (especially those of 680 at Constantinople and of 787 at Nicaea [modern İznik, Turkey]) and in the various lists of bishoprics (Notitiae episcopatuum). From these it is clear that ecclesiastical administration in the south, especially in the Peloponnese, had suffered considerably. Many bishoprics were abandoned and had ceased to exist. At the council of 680, only 4 bishops from that region (Athens, Corinth, Lakedaimon, and Árgos) and 12 from Macedonia attended; what is believed to be a 7th-century episcopal list (the Pseudo-Epiphanios) records the names of only 5 metropolitan bishops from Greece, mostly from the north.<br>

        Administratively, those districts that remained under Byzantine control were organized from the later 7th century onward into the military province, or theme (Greek: thema), of Hellas, under its general (strategos). The theme initially encompassed only the easternmost parts of central Greece but gradually included parts of Thessaly and, possibly, of the Peloponnese, although in the latter case only the coastal regions were involved.<br>

        The islands of the Aegean remained largely in Byzantine hands. In late antiquity they had been relatively heavily populated, the larger ones among them—especially Lemnos (Límnos) and Thasos (Thásos) in the north—being well-known sources of agricultural produce. Arab piracy and raiding from the later 7th century onward altered this, causing many of the smaller islands to become deserted; however, the islands recovered during the 10th century.<br>


        Byzantine fortress-towns testify to the presence of sizable rural populations needing shelter from attack; the towns also served as refuges for people from the mainland fleeing Avar, Slav, or Bulgar raids. Administratively, in the second half of the 7th century they formed a component of the districts allotted to the naval theme (in the original sense of the term—an “army”) of the Karabisianoi (Greek: karabos, a light ship), which represented the rump of the quaestura exercitus (the Roman military command comprising the Islands, Caria, and Moesia II). During the first half of the 8th century this command appears to have been subdivided to form the naval themes of the Kibyrrhaiotai (including parts of western Asia Minor and named after the district and town of Kibyrrha in southwestern Asia Minor), Samos (Sámos), or the Kólpos (“Gulf”) in the southern zone, and Aigaion Pelagos covering the northern districts. Further subdivisions took place in the 10th–12th century, so that commands of the Dodecanese (Dodekánisa) Islands or the Cyclades (Kykládes) also appear in the sources.<br>

        It must be stressed that, even though the archaeological record clearly supports the conclusion that a dramatic collapse of traditional urban society and economic relations occurred, it also gives evidence of significant regional variations. The process of change was neither uniform across Greece nor was it always as extreme in one area as in another. The degree of access to imperial resources and the ability to maintain regular contact with the imperial government were factors that gave some areas a very different appearance from others. It is important that this be borne in mind when considering the history of the various regions of Greece in the following period.
        </P>
        <h5>Byzantine recovery</h5>
        <p>
        The Byzantine recovery of lost provinces began toward the end of the 8th century. The emperor Nicephorus I is traditionally credited with a major role in this, although the process was certainly under way before his accession. The degree of Slavicization appears to have varied considerably. For example, it is clear that by the 10th century many districts of the Peloponnese (Pelopónnisos) were Hellenized and Christianized, yet outposts of Slavic language and culture—sometimes partly Hellenized, often independent of central imperial control—survived in the less-accessible regions until the 13th and 14th centuries and perhaps beyond. Traces of the preconquest social and political structures of the northern Peloponnese may be reflected in the story of the widow Danelis, a rich landowner whose wealth was almost proverbial in the later 9th century and who may have represented the last in a line of Christianized but semiautonomous Slavic magnates who had dominated the region around Pátrai (Patras) in Achaea. She was a sponsor of the young Basil, later Basil I.<br>

        Different parts of Greece were reconquered at different times. Epirus (Ípeiros) in the northwest was gradually placed under Byzantine military administration, which was advancing inland from the coast during the first part of the 9th century. The themes of Cephallenia (Kefallinía) and Dyrrachium (Durazzo; modern Durrës, Albania) had been established by the 830s, and that of Nikopolis appeared at the end of the 9th century. The theme of the Peloponnese emerged as a separate region in 812, although it was almost certainly created before this date; that of Thessalonica (Thessaloníki) had probably been established by about 812 as well, although this remains debated; those of Strymon (Strymónas) and Boleron appeared likewise during the course of the 9th century. Crete, part of which had fallen to the Arabs in 824, would not be wholly regained by Byzantium until 961.<br>

        Ecclesiastical organization once again reflects this process. A 9th-century list of bishoprics contains 10 Greek metropolitan sees, including those of Patras and Athens, compared with the 5 that appear in earlier records. During the first half of the 8th century (in the context of the Iconoclastic Controversy, a religious controversy concerning the veneration of icons, or sacred images), the ecclesiastical provinces of the old prefecture of Illyricum, which had been subject to Rome, were withdrawn from papal authority by the emperor Leo III and placed under Constantinople, thus permitting a unified program of re-Christianization of much of this region.<br>

        As Byzantine control became firmer, and as Byzantine military and political expansion northward accelerated during the 10th and early 11th centuries, older themes were subdivided, forming a mosaic of small administrative divisions. Thus, the themes of Berroia, Drougoubiteia (clearly reflecting a Slavic tribal territory), Jericho (on the Adriatic coast between Dyrrachion and Nikopolis), and Edessa (Édhessa) or Vodena (northwest of Thessalonica) all appeared during the period from the late 9th to the 11th century.
        </p>
        <h5>Economy and society</h5>
        <p>
        Like other regions of the Byzantine Empire, Greece had suffered economically from the warfare of the 7th and 8th centuries. The rise of the khanate of the Bulgars, established south of the Danube after 681, whose rulers were able to exercise a hegemony over their politically fragmented Slavic neighbours, meant that warfare remained endemic and economic insecurity a factor of daily existence. However, the restoration of Byzantine military and political power from the later 8th century onward and the growth of Byzantine cultural and religious influence throughout the Balkans during the 9th and 10th centuries created a context favourable to economic and demographic recovery throughout the empire, especially in the southern Balkan region. During the 11th and 12th centuries Greece experienced a powerful economic upswing, certainly more so than Anatolia. Cities such as Thessalonica (Thessaloníki), Thebes (Thíva), and Corinth (Kórinthos) became centres of flourishing local industries and of market exchange, rivaling the imperial capital in many respects. The silk industry that developed around Thebes was especially important. The evidence for greater wealth, especially greater disposable wealth, in the hands of local elites is found not only in documentary sources but also in a number of endowed churches, some of which are still in existence today. Many other towns, particularly those with a harbour or shelter for ships, became flourishing centres of trade and commerce and were sought-after locations for the trading posts of the Italian merchant republics after the 11th century.
        </p>
        <h5>
        Results of the Fourth Crusade
        </h5>
        <p>
          The Fourth Crusade, called by Pope Innocent III to reconquer the Holy Land, was diverted to Constantinople. Following the Crusaders’ seizure and sack of the city in 1204, the European territories of the Byzantine Empire were divided up among the Western magnates. Whereas Byzantine resistance in Asia Minor was successful, so that two independent successor empires were established (those of Nicaea and Trebizond), most of Greece was quickly and effectively placed under Frankish (Western Christian) rule. The principality of Achaea (the Morea) and the Latin duchy of the Archipelago were subject to the Latin emperor, who was the ruler of the Latin Empire (also referred to as Romania) set up in Constantinople in 1204 by the Latin (Western) Christians of the Fourth Crusade and claimed jurisdiction over the territories of the Byzantine state. A kingdom of Thessalonica was established, to whose ruler the lords of Athens and Thebes owed fidelity, while the county of Cephallenia (Kefallinía)—which, along with the islands of Ithaca (Itháki) and Zacynthus (Zákynthos), had in fact already been under Italian rule since 1194, under Matteo Orsini—was nominally subject to Venice, although it was autonomous and after 1214 recognized the prince of Achaea as overlord. Finally, the lord of Euboea (Évvoia, or Negroponte) was subject to the authority of both Thessalonica and Venice. Byzantine control remained in the form of the despotate of Epirus in the northwest, in the area around Monemvasía in the eastern Peloponnese, and in the mountain fastness of the Taïyetos in Achaea and Arcadia (Arkadía). In 1261, however, the Nicaean forces were able to recover Constantinople and put an end to the Latin Empire. The recovery of some of the territory held by Frankish rulers followed, although Monemvasía actually fell, for a while, to a Frankish force in 1248. By the end of the 13th century, parts of central Greece were once again in Byzantine hands, and the Byzantine despotate of the Morea controlled much of the central and southeastern Peloponnese, but to its north the principality of Achaea remained an important Frankish power.<br>
          The history of Greece reflects very closely its geopolitical structure. This fact is particularly clear in the period following the Fourth Crusade, when the former Byzantine administrative divisions were organized into various petty states, each having its own local history and political evolution.
        </p>
        <h5>Despotate of Epirus</h5>
        <p>
        The so-called despotate of Epirus (ruled by a despotēs, or lord), which usually included Cephallenia (Kefallinía), was established by Michael I Komnenos Doukas, who established effective control after 1204 over northwestern Greece and a considerable part of Thessaly. His brother and successor Theodore was able to retake Thessalonica from the Latins in 1224, where he was crowned as emperor, thus challenging the emperor of Nicaea, who claimed imperial rule. However, in 1242 the Nicaean ruler John III Ducas Vatatzes compelled Theodore’s son and successor John to abandon the title of emperor, and by 1246 Thessalonica was under Nicaean rule. In 1259 much of Epirus came under Nicaean control, but this was lost by 1264. Thereafter Epirus continued to be ruled by independent despots (despotai) until 1318. Its sheltered geographic position, between the spine of the Pindus mountain range and the Adriatic Sea, facilitated a degree of political separatism and independence from Constantinople until the Ottoman conquest. The Byzantine emperors, however, always insisted on their rights to confer the title of despotēs, and for much of the 14th and 15th centuries they regarded the rulers of Epirus as rebels.<br>

        From 1318 until 1337 Epirus was ruled by the Italian Orsini family, and after a short Greek recovery it was taken by the Serbs in 1348, and Ioánnina and Árta were its main political centres. From 1366 to 1384 Ioánnina was ruled by Thomas Komnenos Palaeologus, also known as Preljubovič, the son of the caesar Gregory Preljub, who had been the Serbian governor of Thessaly under Stefan Uroš IV Dušan. He was able to assert Serbian control over northern Epirus and fought with the Albanian lords of Árta (Ghin Bua Spata and Peter Ljoša) in the south, eventually defeating them with the aid of the Ottomans. In 1382 his title of despotēs was confirmed by the Byzantine emperor at Constantinople. He was assassinated late in 1384, probably by members of the local nobility who objected to his rule. His widow, the Byzantine Maria Angelina Doukaina Palaiologina, married the Italian nobleman Esau Buondelmonti, who ruled as despotēs until about 1411. Thereafter the despotate came under the Italian house of Tocco, whose rulers were able to recover Árta from the Albanians. But in 1430 the Ottomans took Ioánnina and in 1449 they captured Árta, and, thus, Epirus became part of the Ottoman Empire. Cephallenia was taken in 1479, but Venice seized it in 1500.
        </p>
        <h5>Thessaly and surrounding regions</h5>
        <p>The political history of the other regions of Greece during this period is no less complex. Thessaly was ruled in its eastern parts by the Franks after 1204, while the western regions were disputed by the rulers of Epirus and Nicaea. About 1267 John I Doukas established himself as an independent ruler, with the Byzantine title sebastokrator, at Neopatras, but in expanding his control eastward he came into conflict with Michael VIII, whose attacks he repelled with the assistance of the dukes of Athens and Charles I of Anjou. Venetian support, the result of a favourable trading relationship (Thessaly exported agricultural produce), helped maintain Thessalian independence until the arrival in 1309 of the Catalan Grand Company. That band of Spanish mercenaries, who originally had been hired by Andronicus II to fight the Seljuqs in Anatolia turned against imperial authority and established themselves in the Gallipoli peninsula. From there they moved into Greece through Thrace and Macedonia, which they plundered, and from 1318 onward they occupied the southern districts of Thessaly. The northern regions remained independent under the ruler Stephen Gabrielopoulos until 1332, and then they were taken by John II Orsini of Epirus. In 1335 Thessaly was retaken by the Byzantine Empire, and from 1348 it acknowledged the overlordship of the Serbian ruler Stefan Dušan. After his death (1355) the self-styled emperor Symeon Uroš, despotēs of Epirus and Akarnania, was able to seize control of both Epirus and Thessaly and rule independently following the death of Nikephoros II in 1358/59. He was succeeded by his son John, who adopted the monastic life in 1373. The caesar Alexios Angelos Philanthropenos took control, governing as a vassal of the Byzantine emperor John V, but in 1393 the conquest of Thessaly by Ottoman forces put an end to its independence.</p>
        <h5>Athens, Thebes, and Corinth</h5>
        <p>In the south, Greece was divided among a number of competing political units. After 1204 the dukes of Athens (mostly of French or Italian origin) controlled much of central Greece, with their main base at Thebes. They had political interests to the north and in the Peloponnese. However, in 1311 the Catalan Grand Company established its power over the duchies of Athens and Thebes, turning out their Latin lords. Under the protection of the Aragonese king Frederick II of Sicily (three sons of whom became dukes of Athens), they dominated the region until the Navarrese Company (an army of mercenaries originally hired by Luis of Evreux, brother of Charles II of Navarre, to help assert his claim over Albania and then temporarily in the service of the Hospitallers, a military-monastic order) took Thebes in 1378 or 1379. This weakened Catalan power and opened the way for the Florentine Acciajuoli, lords of Corinth, to take Athens in 1388. The latter then ruled all three regions until their defeat at the hands of the Ottomans in the 1450s.</p>
        <h5>The Peloponnese</h5>
        <p>In the Peloponnese the political rivalry between the Byzantines and the Frankish principality of Achaea dominated. The principality was at its most successful under its prince William II Villehardouin (1246–78), but in 1259 he had to cede a number of fortresses, including Mistra, Monemvasiá, and Maina, to the Byzantines. Internecine squabbles weakened resistance to Byzantine pressure, especially from the 1370s onward, when Jacques de Baux hired the Navarrese Company to fight for his claim to the principality. Upon his death in 1383, the Navarrese exercised effective political control over the Frankish territories under the commanders of the company. The last Navarrese prince, Pierre de Saint-Superan, joined the Ottomans in 1401 to raid Byzantine possessions in the southern Peloponnese; he died in 1402. He was succeeded by his widow, Maria Zaccaria, representative of an important Genoese merchant and naval family. She passed the title to her nephew Centurione II Zaccaria, who lost much of the territory to the Byzantine despotate of the Morea. In 1430 he married his daughter to the Byzantine despotēs Thomas Palaeologus, handing over his remaining lands as her dowry. From that time on, the Byzantine despotate of the Morea effectively controlled most of the Peloponnese. However, the Ottoman presence and the fall of Constantinople to Sultan Mehmed II in 1453 effectively ended that final period of Byzantine rule. The Morea resisted Ottoman conquest until 1460, when it was finally incorporated into the Ottoman Empire (a year earlier than the empire of Trebizond, which fell in 1461). All of Greece was by that time under Ottoman authority, with the exception of some of the islands, which retained a tenuous independence under Venetian or Genoese protection.</p>
        <h5>Serbian and Ottoman advances</h5>
        <p>Byzantine power in the northern Greek regions was effectively destroyed by the expansion of the Serbian empire under Stefan Dušan, the results of which included the loss of Epirus, Thessaly, and eastern Macedonia. From the 1350s the Ottomans established themselves in Europe, taking the chief towns of Thrace in the 1360s and Thessalonica in 1387. Apart from the despotate of the Morea, therefore, and certain of the Aegean isles, there remained in Greece no Byzantine imperial possessions by the beginning of the 15th century.</p>
        <h5>The islands
</h5>
<p>A particularly complex picture is represented by the islands, which were a focus for the activities of the Seljuqs and later the Ottomans, the Venetians and Genoese, and the Byzantines. Following the Fourth Crusade, much of the southern part of the Aegean came under Venetian authority, and, although Byzantine power was restored for a while in the late 13th century, Náxos (Náchos) remained the centre of the Latin duchy of the Archipelago, established in 1207 among the Cyclades by Marco Sanudo, a relative of the Venetian doge, or magistrate, with a body of plundering merchants and nobles. Initially under the overlordship of the Latin emperor at Constantinople, the duchy later transferred its allegiance to Achaea in 1261 and to Naples in 1267, although Venice also claimed suzerainty. The Sanudo family was replaced in 1383 by the Lombard Crispi family, which retained its independence until 1566. At that time the duchy was conquered by the Ottomans, although it was ruled by an appointee of the sultan until 1579, when it was properly incorporated into the state.<br>

The remaining islands were held at different times by the Venetians, the Genoese, the Hospitallers, and the Turks. Rhodes played a particular role in the history of the Hospitallers’ opposition to the Ottomans. Until the early 13th century the island had been in the hands of a succession of Italian adventurers, most of whom acknowledged the overlordship of the emperor at Nicaea. In 1308 the Hospitallers took control, having been based on Cyprus since 1291, the time of their expulsion from the Holy Land. Rhodes fell in 1523, when the Hospitallers were permitted to remove to Malta. Of the northern Aegean islands, Lemnos remained Byzantine until 1453 before coming for a while under the rule of the Gattilusi of Lésbos, whose independence of the Ottomans ended in 1462. In 1460 it was awarded to Demetrius Palaeologus, formerly despotēs of the Morea, along with the island of Thasos (the latter having come under Ottoman domination in 1455). In 1479 it was occupied by Ottoman forces and officially incorporated into the Ottoman state. Other islands had equally checkered histories. Náxos and Chíos (Khíos) fell in 1566, although complete Ottoman control was not achieved until 1715, when Tenedos, which remained under Venetian control until that year, was taken.<br>
The real exception to the Ottoman success in the Aegean, however, was Crete. Separately administered until the 820s, when it was seized by Spanish Arabs, it was conquered in 961 by the general and later Byzantine emperor Nicephoros II Phocas. After 1204 it was handed over to Boniface of Montferrat, who proceeded to sell it to Venice. Although oppressive and unpopular, Venetian rule witnessed the evolution of a flourishing Italo-Hellenic literary and political culture. After a long siege of Candia (now Irákleio) and the creation and collapse of temporary alliances between Venice and various Western powers on the one hand and the Ottomans and their supporters on the other, the island passed into Ottoman hands in 1669.
</p>
<h5>
Economic and social developments
</h5>
<p>
In spite of the political instability after 1204, Greece seems to have experienced relative prosperity in the later Byzantine period. Population expansion accompanied an increase in production as marginal lands were brought under cultivation, and trade with major and minor Italian mercantile centres flourished. Although hostility at the level of state politics was endemic, social relations between the ruling elites of Byzantine- and Latin-dominated areas were not mutually exclusive. Intermarriage was not uncommon, and a certain way of life seems to have evolved. This contrasted with the attitude of the peasantry and the ordinary population, whose perceptions were shaped by the Orthodox church, Greek or Byzantine (“Roman”) identity, and hostility to the Western church and its ways. The Ottoman conquest was not seen as necessarily worse than Latin domination. In some cases it was certainly welcomed as less oppressive.
</p>
<h4>Cultural continuity</h4>
<p>The history of medieval Greece has played an important part in attempts to understand the relationship between ancient and modern Greece. The issue of the continuity between ancient and modern Greeks has been an extremely controversial one, in both scholarly and political contexts. The claim that modern Greeks are the direct cultural and biological descendants of the “ancient Hellenes” has long been a central tenet of the national ideology on which the Greek state was founded. Scholars such as the Austrian-born 19th-century German historian Jakob Fallmerayer argued that, as a result of the large Slav and Albanian invasions during the medieval period, the latter-day population of Greece could not be entirely of Greek “racial” origin. Greek scholars in such diverse disciplines as archaeology, linguistics, folklore, and history have attempted to identify “survivals” from ancient Greek culture that can still be found in its modern counterpart. Although there certainly are significant similarities that demonstrate continuities in some aspects of Greek culture, there are also equally important differences that demonstrate discontinuities in other aspects of Greek culture. Unfortunately, scholarship on this issue has often been overshadowed by nationalist and romantic political agendas of Greeks and non-Greeks alike.</p>
<h5>The Slavs</h5>
<p>From the late 6th to the 8th century, a large number of Slavs entered what is now Greece. Although the evidence of place-names suggests some lasting Slavic influence in parts of Greece, it is qualified by the fact that the process of re-Hellenization that occurred from the later 8th century seems to have eradicated many traces of Slavic presence. Evidence of tribal names found in both the Peloponnese and northern Greece suggests that there were probably extensive Slavic-speaking populations in many districts, and from the 10th to the 15th century Slavic occupants of various parts of the Peloponnese appear in sources as plunderers or as fiercely independent warriors. Whereas the Slavs of the south appear to have adopted Greek, those of Macedonia and Thessaly retained their original dialects, becoming only partially Hellenophone in certain districts.</p>
<h5>The Albanians</h5>
<p>The Albanians in the 14th century began to advance into Greece’s western coastal plain, where they served both Byzantine and Serbian overlords and ruled independently under various warlords and chiefly families. They were also present in considerable numbers in Thessaly, Boeotia, Attica (Attikí), and the Peloponnese, serving as soldiers and farmers and colonizing deserted lands. Albanians arrived in large numbers in the Peloponnese during the reign of the despotēs Manuel Kantakouzenos, who brought them there to serve as soldiers and to resettle depopulated regions. The reason for their migration to these areas remains debated. These early Albanian-speaking settlers constitute a group distinct from the economic migrants from Albania, who settled in Greece in the late 20th and early 21st centuries and who are simply known as “Albanians” (Greek: Alvanoi).</p>
<h5>The Aromani (Aromanians)</h5>
<p>The Aromani (Vlachs) played an important role in central and southern Thessaly. They have generally been identified with the indigenous pre-Slav populations of Dacian and Thracian origin, many of whom migrated into the less-accessible mountainous areas of Greece and the northern Balkan region because of the Germanic and Avar-Slav invasions and immigration of the 5th–7th century. The Aromani maintained a transhumant pastoral economy in those areas. Their language belongs to the so-called Macedo-Romanian group and is closely related to that known from the 13th century on as Romanian (Daco-Romanian). It is essentially rooted in late Latin but heavily influenced by the Slavic dialects with which the Daco-Thracian populations were in regular contact. By the 11th century the Aromani are described as communities of shepherds who moved with their flocks between their winter pastures in Thessaly and summer pastures in Mount Gramoz and the Pindus range. They are found in Byzantine armies and are mentioned in many documents dealing with landholdings in northern Greece, where—as is often the case in relations between settled and nomadic populations—they were regarded as troublemakers and thieves. Byzantines were often imprecise in their use of ethnic names, and the Aromani seem frequently to have been confused with the Bulgarians, through whose territory they also wandered on their seasonal routes and pasturage. A major modern debate about the role of the Aromani in the establishment of the second Bulgarian empire after 1185 continues and is strongly marked by nationalist sentiment.</p>
<h5>Emerging Greek identity</h5>
<p>
As the Byzantine Empire declined, the predominant role of Greek culture, literature, and language became more apparent. For Christians of the early and middle Byzantine worlds, the terms Hellene and Hellenic generally (although not exclusively, since in certain literary contexts a classicizing style permitted a somewhat different usage) had a negative connotation, signifying pagan and non-Christian rather than “Greek.” From the 12th century, however, in the context of increasing conflict with western European culture on the one hand and the encroaching Turkish powers on the other, that situation changed. Gradually, a more self-consciously Greek consciousness began to develop, and a greater interest in “Hellenic” culture in a positive sense eventually evolved. Byzantines began to refer to themselves not just as “Romioi” (literally, “Roman,” referring to members of the Eastern Roman [that is, Byzantine] Empire). In the decades prior to the Greek War of Independence, the Greeks began to identify themselves as “Hellenes” and assert their identity with the ancient Hellenic world. Among learned circles a deep interest in the Classical past was cultivated. Although there was a powerful secularist tradition in this, culminating in the ideas of the Neoplatonic Byzantine philosopher George Gemistus Plethon, who argued for the implementation of the political-philosophical system outlined in Plato’s Republic, it was the combination of popular Orthodoxy (and strongly anti-Western ecclesiastical sentiment) with a specifically Greek identity that shaped the Byzantines’ notions of themselves in the twilight years of the empire. With the political extinction of the empire, it was the Greek Orthodox Church and the Greek-language community, in both “Greece” and Asia Minor, that continued to cultivate this identity as well as the ideology of a Byzantine imperial heritage rooted in both the Roman and the Classical Greek past.
</p>
<h4>Greece under Ottoman rule</h4>
<p>Constantinople fell to the Ottoman Turks on May 29, 1453. The Byzantine emperor, Constantine XI Palaeologus, was last seen fighting alongside his troops on the battlements. His death gave rise to the widely disseminated legend that the emperor had turned to marble but would one day return to liberate his people. By 1453 the Byzantine Empire had become but a pathetic shadow of its former glories. The fall of this symbolic bastion of Christendom in the struggle against Islam may have sent shock waves through Western Christendom, but the conquest was accepted with resignation by many of the inhabitants of the city. As they saw it, their plight was a consequence of the sinfulness of the Byzantine Empire. For many people, Ottoman rule and the maintenance of the integrity of the Orthodox faith were preferable to accepting the pretensions of the papacy, which was the price Western Christendom had sought to exact in return for military assistance to ward off the Turkish threat.</p>
      </section>
      <section class="currentEvents topic" id="greeceCurrentEvents">
        <h3>Headlines About ${state.info.name}</h3>
        <p>${state.news.data.map(newsCard)}</p>
      </section>
    </div>
  </div>
`;
const newsCard = data =>
  html`
    <h1>
      ${data.title}
    </h1>
    <a href="${data.url}">Click Here To Learn More</a>
  `;
const weatherBlock = weather =>
  html`
    <u>${weather.description}</u>
  `;
