export { default as Header } from "../components/Header";
export { default as Main } from "../components/Main";
export { default as Nav } from "../components/Nav";
export { default as Footer } from "../components/Footer";
export { default as Translator } from "../components/Translator";
export { default as Belarus } from "../components/countries/Belarus";
export { default as Japan } from "../components/countries/Japan";
export { default as Morocco } from "../components/countries/Morocco";
export { default as Usa } from "../components/countries/Usa";
