# MAKES A DIRECTORY FOR EACH COUNTRY AND TXT FILES FOR THEM
mkdir bh && cd bh && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bs && cd bs && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bd && cd bd && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bb && cd bb && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir by && cd by && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir be && cd be && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bz && cd bz && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bj && cd bj && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bm && cd bm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bt && cd bt && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bo && cd bo && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bq && cd bq && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ba && cd ba && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bw && cd bw && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bv && cd bv && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir br && cd br && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir io && cd io && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bn && cd bn && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bg && cd bg && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bf && cd bf && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bi && cd bi && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir kh && cd kh && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cm && cd cm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ca && cd ca && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cv && cd cv && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ky && cd ky && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cf && cd cf && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir td && cd td && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cl && cd cl && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cn && cd cn && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cx && cd cx && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cc && cd cc && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir co && cd co && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir km && cd km && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cg && cd cg && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cd && cd cd && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ck && cd ck && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cr && cd cr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ci && cd ci && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir hr && cd hr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cu && cd cu && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cw && cd cw && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cy && cd cy && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir cz && cd cz && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir dk && cd dk && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir dj && cd dj && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir dm && cd dm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir do && cd do && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ec && cd ec && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir eg && cd eg && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sv && cd sv && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gq && cd gq && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir er && cd er && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ee && cd ee && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir et && cd et && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir fk && cd fk && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir fo && cd fo && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir fj && cd fj && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir fi && cd fi && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir fr && cd fr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gf && cd gf && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pf && cd pf && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tf && cd tf && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ga && cd ga && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gm && cd gm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ge && cd ge && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir de && cd de && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gh && cd gh && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gi && cd gi && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gr && cd gr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gl && cd gl && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gd && cd gd && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gp && cd gp && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gu && cd gu && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gt && cd gt && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gg && cd gg && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gn && cd gn && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gw && cd gw && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gy && cd gy && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ht && cd ht && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir hm && cd hm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir va && cd va && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir hn && cd hn && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir hk && cd hk && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir hu && cd hu && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir is && cd is && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir in && cd in && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir id && cd id && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ir && cd ir && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir iq && cd iq && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ie && cd ie && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir im && cd im && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir il && cd il && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir it && cd it && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir jm && cd jm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir jp && cd jp && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir je && cd je && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir jo && cd jo && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir kz && cd kz && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ke && cd ke && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ki && cd ki && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir kp && cd kp && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir kr && cd kr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir kw && cd kw && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir kg && cd kg && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir la && cd la && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir lv && cd lv && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir lb && cd lb && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ls && cd ls && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir lr && cd lr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ly && cd ly && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir li && cd li && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir lt && cd lt && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir lu && cd lu && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mo && cd mo && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mk && cd mk && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mg && cd mg && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mw && cd mw && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir my && cd my && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mv && cd mv && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ml && cd ml && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mt && cd mt && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mh && cd mh && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mq && cd mq && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mr && cd mr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mu && cd mu && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir yt && cd yt && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mx && cd mx && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir fm && cd fm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir md && cd md && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mc && cd mc && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mn && cd mn && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir me && cd me && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ms && cd ms && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ma && cd ma && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mz && cd mz && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mm && cd mm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir na && cd na && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir nr && cd nr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir np && cd np && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir nl && cd nl && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir nc && cd nc && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir nz && cd nz && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ni && cd ni && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ne && cd ne && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ng && cd ng && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir nu && cd nu && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir nf && cd nf && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mp && cd mp && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir no && cd no && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir om && cd om && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pk && cd pk && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pw && cd pw && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ps && cd ps && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pa && cd pa && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pg && cd pg && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir py && cd py && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pe && cd pe && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ph && cd ph && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pn && cd pn && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pl && cd pl && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pt && cd pt && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pr && cd pr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir qa && cd qa && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir re && cd re && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ro && cd ro && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ru && cd ru && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir rw && cd rw && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir bl && cd bl && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sh && cd sh && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir kn && cd kn && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir lc && cd lc && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir mf && cd mf && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir pm && cd pm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir vc && cd vc && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ws && cd ws && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sm && cd sm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir st && cd st && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sa && cd sa && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sn && cd sn && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir rs && cd rs && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sc && cd sc && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sl && cd sl && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sg && cd sg && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sx && cd sx && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sk && cd sk && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir si && cd si && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sb && cd sb && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir so && cd so && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir za && cd za && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gs && cd gs && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ss && cd ss && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir es && cd es && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir lk && cd lk && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sd && cd sd && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sr && cd sr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sj && cd sj && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sz && cd sz && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir se && cd se && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ch && cd ch && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir sy && cd sy && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tw && cd tw && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tj && cd tj && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tz && cd tz && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir th && cd th && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tl && cd tl && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tg && cd tg && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tk && cd tk && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir to && cd to && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tt && cd tt && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tn && cd tn && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tr && cd tr && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tm && cd tm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tc && cd tc && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir tv && cd tv && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ug && cd ug && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ua && cd ua && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ae && cd ae && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir gb && cd gb && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir us && cd us && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir um && cd um && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir uy && cd uy && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir uz && cd uz && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir vu && cd vu && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ve && cd ve && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir vn && cd vn && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir vg && cd vg && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir vi && cd vi && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir wf && cd wf && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir eh && cd eh && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir ye && cd ye && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir zm && cd zm && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
mkdir zw && cd zw && touch culture.txt demographics.txt economy.txt geography.txt government.txt history.txt && cd ../
